on:
  # Run every 12 hours
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run scraper
      run: |
        python scraper/main.py
    
    - name: Clean and Merge New Data
      run: |
        python analysis/main.py
    
    - name: Retrain model 
      run: |
        python ml/main.py

    - name: List directory
      run: ls -R

    - name: Checkout branch
      run: git checkout modifying_scraper


    - name: Commit and push output file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add output file from scraper"
        git push
